CREATE TABLE IF NOT EXISTS Item (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    descricao TEXT NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS User (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);